### ISSUE TITLE
支持 xcode 6.3.1 吗

### ISSUE THREAD

**Issue by masakapa** [MakeZL/ZLGotoSandboxPlugin#2]
支持 xcode 6.3.1 吗？我无发允许该项目，安装不了。

**Comment by MakeZL** [comment]
我更改了UUID, 你试试可以吗？

**Comment by masakapa** [comment]
![qq20150511-1 2x](https://cloud.githubusercontent.com/assets/6830671/7560675/ed72af88-f7f7-11e4-998e-4878c291a795.png)

**Comment by MakeZL** [comment]
好的~ 我今天下载下最新的XCode6.3.1来试试，然后给你答复。

**Comment by masakapa** [comment]
对了，这个问题是出在新下载的xcode 上，无法编译报错。之前xcode安装了ZLGotoSandboxPlugin升级到6.3.1 是没有问题的

**Comment by MakeZL** [comment]
我更改了下安装的目录，我怀疑你更改目录权限有点问题。如果不行，点 磁盘工具 ，修复权限试试

**Comment by masakapa** [comment]
确实是权限问题  sudo chmod -R 777 /Users/XXX/Library/
