### ISSUE TITLE
It unwork in iOS9

### ISSUE THREAD

**Issue by DexSinis** [MakeZL/ZLGotoSandboxPlugin#8]
(null):iOS9Sampler > MakeZL: In the Run Simulation. iOS8 No support Chinese. (You look >> File -> go to sandbox)

**Comment by MakeZL** [comment]
Xcode Sandbox mechanism , Must be App info.plist Identifier is EqualTo Project Name Otherwise Can not use shortcut keys.

**Comment by MakeZL** [comment]
): Sorry, I can't think of any other way.
